name: Schedule Prebuild Docker

on:
  schedule:
    - cron: '01 01 * * *'
  workflow_dispatch:
  push:
    paths-ignore:
      - '*.md'
      - '.github/**'
      - 'LICENSE'
      - '*.mmdb'
      - '*.xz'
      - '*.md5sum'
      - '*.sha256sum'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@main
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@main
      - name: Build and push
        uses: docker/build-push-action@master
        with:
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.AWS_MMDB_RUNNER }}
