name: data-update

on:
  workflow_dispatch:
  schedule:
    - cron: '00 01 * * 4'
permissions:
  contents: write

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@main
    - name: "Configure AWS Credentials"
      uses: aws-actions/configure-aws-credentials@main
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@main
    - name: Update data
      run: docker run -v $(pwd):/data -e YOUR_ACCOUNT_ID=${{ secrets.YOUR_ACCOUNT_ID }} -e YOUR_LICENSE_KEY=${{ secrets.YOUR_LICENSE_KEY }} ${{ secrets.AWS_MMDB_RUNNER }}
    - uses: EndBug/add-and-commit@main
      with:
        author_name: Github Actions
        author_email: actions@github.com
        committer_email: actions@github.com
    - uses: kkkgo/Clean-Git-File-History-Action@main
      with:
        size_threshold: 10M
        filenames: '*.mmdb,*.xz,*.dat,*.md5sum,*.sha256sum'
    - name: Flash CDN
      run: |
          curl -i https://purge.jsdelivr.net/gh/${{ github.repository }}/Country-only-cn-private.mmdb.md5sum &&
          curl -i https://purge.jsdelivr.net/gh/${{ github.repository }}/Country-only-cn-private.mmdb.sha256sum &&
          curl -i https://purge.jsdelivr.net/gh/${{ github.repository }}/Country-only-cn-private.mmdb &&
          curl -i https://purge.jsdelivr.net/gh/${{ github.repository }}/CN-local.dat.md5sum &&
          curl -i https://purge.jsdelivr.net/gh/${{ github.repository }}/CN-local.dat.sha256sum &&
          curl -i https://purge.jsdelivr.net/gh/${{ github.repository }}/CN-local.dat &&
          curl -i https://purge.jsdelivr.net/gh/${{ github.repository }}/geosite.dat &&
          curl -i https://purge.jsdelivr.net/gh/${{ github.repository }}/geosite.dat.sha256sum &&
          curl -i https://purge.jsdelivr.net/gh/${{ github.repository }}/geosite.dat.xz &&
          curl -i https://purge.jsdelivr.net/gh/${{ github.repository }}/geosite.dat.xz.sha256sum
